name: faithconnect
description: "A platform where Worshipers connect with their Religious Leaders."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase Core
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.7.0   # âœ… REQUIRED for reels

  # ðŸŽ¥ Media & Video
  image_picker: ^1.0.7        # Pick video from gallery
  video_player: ^2.8.2        # Play reels

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
